apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    humanitec.com/orgId: riansorg
    humanitec.com/appId: 5min-idp-tshr
  name: deployed-fixed
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis:
    - example-grpc-api
